name: Pure Win64 Build
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 自动安装 3proxy 缺少的 PCRE2 和 OpenSSL 依赖库
      - name: Install dependencies
        run: |
          vcpkg install pcre2:x64-windows-static openssl:x64-windows-static

      # 设置微软官方的 MSVC 编译环境
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      # 执行编译，并引入刚才安装的依赖库路径
      - name: Compile 3proxy
        shell: cmd
        run: |
          set "LIB=%LIB%;C:\vcpkg\installed\x64-windows-static\lib"
          set "INCLUDE=%INCLUDE%;C:\vcpkg\installed\x64-windows-static\include"
          nmake -f Makefile.msvc

      # 打包成品供你下载
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-免杀-3proxy
          path: src/*.exe
